CONNECT sys/ALTIS@XE AS SYSDBA
ALTER SESSION SET "_oracle_script"=TRUE;
DROP USER MASTER CASCADE;

CREATE USER MASTER
IDENTIFIED BY ALTIS
DEFAULT TABLESPACE "DADOS"
TEMPORARY TABLESPACE "TEMPO"
QUOTA UNLIMITED ON DADOS
QUOTA UNLIMITED ON INDICES
ACCOUNT UNLOCK
PROFILE "DEFAULT"; 
alter profile DEFAULT limit password_life_time UNLIMITED;
grant all privileges to MASTER;

EXIT
